name: jesus_dart
environment:
  sdk: '^2.13.0'
dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  logger: ^1.3.0
  translator: ^0.1.7
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
